---
- name: unarchive artifact
  unarchive:
    src: files/artifact.tar.gz
    dest: ~/backend

- name: start app
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
