---
- name: unarchive artifact
  unarchive:
    src: files/artifact.tar.gz
    dest: ~/

- name: start app
  shell: |
    cd ~/artifact
    npm install
    pm2 stop default
    pm2 start npm -- start
