---
- name: unarchive artifact
  unarchive:
    src: files/artifact.tar.gz
    dest: ~/

- name: start app
  shell: |
    cd ~/
    npm install
    pm2 stop default
    npm run start:prod
    #pm2 start npm -- start
