---
- name: set up environments variables
  script:
    cmd: files/secrets.sh
    executable: source

- name: "install nodejs"
  apt:
    name:
      - nodejs
      - npm

- name: install pm2
  shell: |
    npm install pm2 -g
    echo $TYPEORM_ENTITIES
