---
- name: set up environments variables
  shell: |
    echo secrets.txt >> ~/.bashrc

- name: "install nodejs"
  apt:
    name: 
      - nodejs
      - npm

- name: install pm2
  shell: npm install pm2 -g