---
- name: set up environments variables
  copy:
    src: files/secrets.sh
    dest: ~/secrets.sh

# - name: load secret
#   shell: |
#     cat ~/secrets.sh >> ~/.bashrc
#     source ~/.bashrc

- name: "install nodejs"
  apt:
    name:
      - nodejs
      - npm

- name: install pm2
  shell: |
    npm install pm2 -g
    echo $TYPEORM_ENTITIES
